### ISSUE TITLE
使用 Scoop 从 0.3.9 升级到 0.3.10 出错

### ISSUE THREAD

**Issue by FDUZS** [zu1k/nali#104]
之前安装时没这个问题，升级时发现 Windows Security 弹了个通知然后下载的文件被删了导致升级失败。
不知道你是否有空分析一下原因？

系统环境
Edition	Windows 11 Pro
Version	21H2
Installed on	‎11/‎23/‎2021
OS build	22000.675
Experience	Windows Feature Experience Pack 1000.22000.675.0

<img width="960" alt="ofc0ATMRDn" src="https://user-images.githubusercontent.com/20297872/168519442-fe27128c-bdda-4bf5-9567-bf336a8bd506.png">

**Comment by zu1k** [comment]
scoop不是我在维护的，我也不太清楚。看起来像是误报病毒了

**Comment by FDUZS** [comment]
对，手动从 release 下载也会被报毒然后删除，不过 Scoop 那边应该是无能为力的。

**Comment by zu1k** [comment]
这个我应该解决不了，不知道为啥报毒，用 github action 直接编译上传的。先关闭这个 issue 了
