### ISSUE TITLE
[feature request] 提供api查询接口

### ISSUE THREAD

**Issue by fcwys** [zu1k/nali#108]
希望支持以web服务运行提供简易api查询接口，例如以文本或json格式输出，性能应该还不错，不知道是否有计划呢，谢谢！

**Comment by zu1k** [comment]
暂时不考虑提供web接口，可以自己封装一下

https://github.com/missdeer/ifconfig 使用了 nali/packages 下的封装

**Comment by fcwys** [comment]
您好，我添加了web json api，提交了pr，您看下呢

**Comment by zu1k** [comment]
感谢PR，但是我目前不打算使其成为一个 web server，所以我不会接收这个 PR。
我的建议是将这个简易server作为你自己的一个小工具，重开一个项目
