### ISSUE TITLE
mtr 命令显示错位

### ISSUE THREAD

**Issue by selboo** [zu1k/nali#123]
```
# mtr www.baidu.com | nali
```

正常

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/1220576/180363695-76727442-7813-4422-b4c6-27d14659adf0.png">

错位, 没有对齐
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/1220576/180363846-f5461d78-b2b7-4a28-880d-d8086b3aeaf9.png">

**Comment by zu1k** [comment]
已知并确定无法修复的问题，请查看历史issue
