### ISSUE TITLE
查询IP出错

### ISSUE THREAD

**Issue by kailuo99** [zu1k/nali#13]
2020/08/24 17:19:42 文件不存在，尝试从网络获取最新ZX IPv6数据库
panic: invalid signature header

goroutine 1 [running]:
github.com/zu1k/nali/pkg/zxipv6wry.Un7z(0xc0000225c0, 0xe, 0x0, 0x0, 0x0, 0x8f83e0, 0xc0000a1670)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:57 +0x61e
github.com/zu1k/nali/pkg/zxipv6wry.getData(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:49 +0x2ca
github.com/zu1k/nali/pkg/zxipv6wry.Download(0xc000024120, 0x1f, 0x1, 0xc0000a00e0, 0x8f8a01, 0xc0000a2210, 0x1f)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:16 +0x34
github.com/zu1k/nali/pkg/zxipv6wry.NewZXwry(0xc000024120, 0x1f, 0x0, 0x0)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/zxipv6wry.go:27 +0xfa
github.com/zu1k/nali/internal/app.InitIPDB(0x1)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/internal/app/parse.go:30 +0x480
github.com/zu1k/nali/cmd.glob..func3(0xbcd0c0, 0xc0000a1a70, 0x1, 0x1)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/cmd/root.go:59 +0x39
github.com/spf13/cobra.(*Command).execute(0xbcd0c0, 0xc0000ae030, 0x1, 0x1, 0xbcd0c0, 0xc0000ae030)
        /home/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xbcd0c0, 0x40748f, 0xc000096058, 0x0)
        /home/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/zu1k/nali/cmd.Execute()
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/cmd/root.go:79 +0x31
main.main()
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/main.go:14 +0x25

**Comment by kailuo99** [comment]
2020/08/24 17:19:42 文件不存在，尝试从网络获取最新ZX IPv6数据库
panic: invalid signature header

goroutine 1 [running]:
github.com/zu1k/nali/pkg/zxipv6wry.Un7z(0xc0000225c0, 0xe, 0x0, 0x0, 0x0, 0x8f83e0, 0xc0000a1670)
        /home/mengmeng/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:57 +0x61e
github.com/zu1k/nali/pkg/zxipv6wry.getData(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mengmeng/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:49 +0x2ca
github.com/zu1k/nali/pkg/zxipv6wry.Download(0xc000024120, 0x1f, 0x1, 0xc0000a00e0, 0x8f8a01, 0xc0000a2210, 0x1f)
        /home/mengmeng/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:16 +0x34
github.com/zu1k/nali/pkg/zxipv6wry.NewZXwry(0xc000024120, 0x1f, 0x0, 0x0)
        /home/mengmeng/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/zxipv6wry.go:27 +0xfa
github.com/zu1k/nali/internal/app.InitIPDB(0x1)
        /home/mengmeng/go/pkg/mod/github.com/zu1k/nali@v0.2.2/internal/app/parse.go:30 +0x480
github.com/zu1k/nali/cmd.glob..func3(0xbcd0c0, 0xc0000a1a70, 0x1, 0x1)
        /home/mengmeng/go/pkg/mod/github.com/zu1k/nali@v0.2.2/cmd/root.go:59 +0x39
github.com/spf13/cobra.(*Command).execute(0xbcd0c0, 0xc0000ae030, 0x1, 0x1, 0xbcd0c0, 0xc0000ae030)
        /home/mengmeng/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xbcd0c0, 0x40748f, 0xc000096058, 0x0)
        /home/mengmeng/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/mengmeng/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/zu1k/nali/cmd.Execute()
        /home/mengmeng/go/pkg/mod/github.com/zu1k/nali@v0.2.2/cmd/root.go:79 +0x31
main.main()
        /home/mengmeng/go/pkg/mod/github.com/zu1k/nali@v0.2.2/main.go:14 +0x25

**Comment by kailuo99** [comment]
2020/08/24 17:19:42 文件不存在，尝试从网络获取最新ZX IPv6数据库
panic: invalid signature header

goroutine 1 [running]:
github.com/zu1k/nali/pkg/zxipv6wry.Un7z(0xc0000225c0, 0xe, 0x0, 0x0, 0x0, 0x8f83e0, 0xc0000a1670)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:57 +0x61e
github.com/zu1k/nali/pkg/zxipv6wry.getData(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:49 +0x2ca
github.com/zu1k/nali/pkg/zxipv6wry.Download(0xc000024120, 0x1f, 0x1, 0xc0000a00e0, 0x8f8a01, 0xc0000a2210, 0x1f)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/update.go:16 +0x34
github.com/zu1k/nali/pkg/zxipv6wry.NewZXwry(0xc000024120, 0x1f, 0x0, 0x0)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/pkg/zxipv6wry/zxipv6wry.go:27 +0xfa
github.com/zu1k/nali/internal/app.InitIPDB(0x1)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/internal/app/parse.go:30 +0x480
github.com/zu1k/nali/cmd.glob..func3(0xbcd0c0, 0xc0000a1a70, 0x1, 0x1)
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/cmd/root.go:59 +0x39
github.com/spf13/cobra.(*Command).execute(0xbcd0c0, 0xc0000ae030, 0x1, 0x1, 0xbcd0c0, 0xc0000ae030)
        /home/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xbcd0c0, 0x40748f, 0xc000096058, 0x0)
        /home/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/xxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/zu1k/nali/cmd.Execute()
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/cmd/root.go:79 +0x31
main.main()
        /home/xxxxxx/go/pkg/mod/github.com/zu1k/nali@v0.2.2/main.go:14 +0x25

**Comment by zu1k** [comment]
查看 https://www.zxinc.org/ 的状态，发现zx数据库的服务器503了，暂时无法从官方下载数据库了

可以先从仓库的db文件夹下下载相应的数据库（版本比较老）
