### ISSUE TITLE
[bug?] nali update 的输出是在 stderr 里

### ISSUE THREAD

**Issue by AnnAngela** [zu1k/nali#131]
我在尝试使用 nodejs 自动化解析 nali 的各项命令的输出结果，但发现 nali update 的输出是在 stderr 里，请问这是 by design 还是哪里手误了？

![image](https://user-images.githubusercontent.com/9762652/183804457-43abf415-6f29-4ad0-ae6d-8d67776f9ed2.png)

**Comment by zu1k** [comment]
预期行为，话说为啥要解析 nali 的 log

https://pkg.go.dev/log
