### ISSUE TITLE
nali IP地址库使用qqwry 报错

### ISSUE THREAD

**Issue by wanglixiang90** [zu1k/nali#137]
./nali 8.8.8.8
panic: runtime error: slice bounds out of range [4:0]

goroutine 1 [running]:
github.com/zu1k/nali/pkg/qqwry.(*QQwry).searchIndex(0x7ffd13760844?, 0xac7a06b6?)
        github.com/zu1k/nali/pkg/qqwry/qqwry.go:122 +0x366
github.com/zu1k/nali/pkg/qqwry.QQwry.Find({{0xc00013eb40, 0x0, 0x1}}, {0x7ffd13760844?, 0xc00011fb40?}, {0x5bc746?, 0x7f7213514008?, 0x8?})
        github.com/zu1k/nali/pkg/qqwry/qqwry.go:75 +0xdb
github.com/zu1k/nali/internal/db.Find(0x995340?, {0x7ffd13760844, 0x7})
        github.com/zu1k/nali/internal/db/db.go:76 +0x7b
github.com/zu1k/nali/pkg/entity.ParseLine({0x7ffd13760844, 0x7})
        github.com/zu1k/nali/pkg/entity/parse.go:58 +0x39f
github.com/zu1k/nali/cmd.glob..func1(0xc37e40?, {0xc000161890, 0x1, 0x1})
        github.com/zu1k/nali/cmd/root.go:77 +0xe5
github.com/spf13/cobra.(*Command).execute(0xc37e40, {0xc00001e050, 0x1, 0x1})
        github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc37e40)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
github.com/zu1k/nali/cmd.Execute()
        github.com/zu1k/nali/cmd/root.go:84 +0x25
main.main()
        github.com/zu1k/nali/main.go:12 +0x2c

解析IP 报错，无法使用了

**Comment by wanglixiang90** [comment]
qqwry.dat 文件大小为零，无法下载。

**Comment by zu1k** [comment]
#112 请自行解决
