### ISSUE TITLE
【功能建议】希望支持go的包模式

### ISSUE THREAD

**Issue by soapffz** [zu1k/nali#144]
如题，希望支持go的包管理模式

导入包，主要功能分函数可调用，不用支持批量，单次引用返回单条记录，返回值[]string比较合适

**Comment by zu1k** [comment]
没有理解你的意思，如果给一个需要的接口示例会更清楚

目前已经有项目导入 nali 了，详见 https://github.com/zu1k/nali/network/dependents ，希望有用

**Comment by zu1k** [comment]
I will close this for long time no update.
