### ISSUE TITLE
release没有维护版本号

### ISSUE THREAD

**Issue by kingcanfish** [zu1k/nali#146]
```
$ nali --version
nali version unknown version

```

**Comment by zu1k** [comment]
请问你下载的版本是哪个，下载链接贴一下

**Comment by zu1k** [comment]
I will close this for long time no update.

**Comment by chaos-cn** [comment]
似乎和通过brew安装有关，我试了直接下载release中的版本是正常的
[~/Downloads]$ ./nali-darwin-arm64 -v
nali version v0.7.1

下面是通过brew安装后的使用信息：
[~]$ nali -v
nali version unknown version

[~]$ nali info
Nali Version:      unknown version
Config Dir Path:   /Users/xxx/Library/Application Support/nali
DB Data Dir Path:  /Users/xxx/Library/Application Support/nali
Selected IPv4 DB:  qqwry
Selected IPv6 DB:  zxipv6wry
Selected CDN DB:   cdn

[~]$ which nali
/opt/homebrew/bin/nali

[~]$ brew info nali
==> nali: stable 0.7.1 (bottled), HEAD
Tool for querying IP geographic information and CDN provider
https://github.com/zu1k/nali
/opt/homebrew/Cellar/nali/0.7.1 (8 files, 8.9MB) *
  Poured from bottle on 2023-02-04 at 21:51:59
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nali.rb
License: MIT
==> Dependencies
Build: go ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 22 (30 days), 76 (90 days), 433 (365 days)
install-on-request: 22 (30 days), 76 (90 days), 432 (365 days)
build-error: 0 (30 days)
