### ISSUE TITLE
nali 0.7.0 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [zu1k/nali#157]
👋 while [regression testing go1.20 upgrade](https://github.com/Homebrew/homebrew-core/pull/122082), I ran into the following error:

```
==> /opt/homebrew/Cellar/nali/0.7.0/bin/nali 1.1.1.1
2023/02/01 23:28:36 文件不存在，尝试从网络获取最新纯真 IP 库
2023/02/01 23:28:36 文件下载失败，请手动下载解压后保存到本地: qqwry.dat 
2023/02/01 23:28:36 下载链接： [https://99wry.cf/qqwry.dat]
2023/02/01 23:28:36 Database init failed: Get "https://99wry.cf/qqwry.dat": dial tcp: lookup 99wry.cf: no such host
```

full build log, https://pipelines.actions.githubusercontent.com/serviceHosts/d065b819-d194-4baa-bc84-7b4a294d8693/_apis/pipelines/1/runs/564571/signedlogcontent/19?urlExpires=2023-02-03T17%3A06%3A38.0355252Z&urlSigningMethod=HMACV1&urlSignature=pSX%2FY%2FAHvb9NFrLSm1xQHLgwZ%2FwQ5NinBMs1z6lh5sI%3D

**Comment by zu1k** [comment]
Thanks, we have updated the download links in v0.7.1.

**Comment by zu1k** [comment]
And this issue is not related to go version 1.20, users can change the download links in the configuration file.

```
# nali info
Nali Version:      0.7.0
Config Dir Path:   /home/zu1k/.config/nali
DB Data Dir Path:  /home/zu1k/.local/share/nali
Selected IPv4 DB:  qqwry
Selected IPv6 DB:  zxipv6wry
Selected CDN DB:   cdn

# vim /home/zu1k/.config/nali/config.yaml
```

**Comment by chenrui333** [comment]
yeah, I know it is not related to go1.20 :)

**Comment by chenrui333** [comment]
Thanks for the new release.
