### ISSUE TITLE
Discussion about json and jsonline implementation

### ISSUE THREAD

**Issue by M09Ic** [zu1k/nali#164]
#163 #80 

The current data structure of result is not uniform, do we need to standardize the format of result in different db first?

For the time being, we can only convert the result in different formats to interface and then json it.

example:
```
{"type":0,"ip":"1.1.1.1","text":"澳大利亚 APNIC/CloudFlare公共DNS服务器","info":{"Country":"澳大利亚","Area":"APNIC/CloudFlare公共DNS服务器"}}
{"type":0,"ip":"2.2.2.2","text":"法国 Orange","info":{"Country":"法国","Area":"Orange"}}
```

The output of the original version is kept in text, while the db details are jsonized as is.

If we want to remove this confusion, we need to first agree on the details of different db result.

**Comment by M09Ic** [comment]
Three-factor output (Country, Region, City): 
* ipip
* ip2location

output example:
```json
{
    "info": {
        "country": "**",
        "region": "**",
        "city": "**"
    }
}
```

Two-factor output (Country, Area): 
* qqwry
* geoip
* xzwry
* ip2region

output example:
```json
{
    "info": {
        "country": "**",
        "area": "**"
    }
}
```

**Comment by M09Ic** [comment]
reference #165

**Comment by zu1k** [comment]
Thank you!
