### ISSUE TITLE
IP数据库能否自定义修改地区跟运营商

### ISSUE THREAD

**Issue by maojianyou** [zu1k/nali#172]
使用的是qqwry.dat纯真IP数据库但里面有些小运营商地址归属不准，能否实现支持自定义运营商

**Comment by zu1k** [comment]
很抱歉，nali 不提供数据库修改的功能，请向数据库维护方反映变更情况

**Comment by maojianyou** [comment]
> 很抱歉，nali 不提供数据库修改的功能，请向数据库维护方反映变更情况

可以自定义一个IP库不，比如第一优先级库，，nali.dat 可以自定义，地区，运营商，然后qqwry.dat为第二数据库，先判断第一IP数据库，然后判断第二通用IP数据库，这样就比较精准，如果向ip数据库维护方反馈流程太长，不灵活

**Comment by zu1k** [comment]
大部分数据库会对不够准确的IP返回一个粗略的结果，对于判断第一IP数据库结果是否有效方面还需要研究一下

**Comment by maojianyou** [comment]
> 大部分数据库会对不够准确的IP返回一个粗略的结果，对于判断第一IP数据库结果是否有效方面还需要研究一下

这个能否优先加个自定义数据库不，比如我私网互联地址比较多，我单独优先判断定义其网络互联地址含义，自行修改private.dat，然后第二判断纯真数据库qqwry.dat，不然很多都不准
