### ISSUE TITLE
通配符规则没有解析

### ISSUE THREAD

**Issue by 4ft35t** [zu1k/nali#18]
https://github.com/zu1k/nali/blob/master/db/cdn.json#L482
```json
  "kunlun(.*).com": {
    "name": "阿里云 CDN",
    "link": "https://www.aliyun.com/product/cdn"
  }
```

一个例子
nslookup asset.watsons.com.cn | nali
Server:		192.168.1.1 [局域网 局域网]
Address:	192.168.1.1 [局域网 局域网]#53

Non-authoritative answer:
asset.watsons.com.cn	canonical name = asset.watsons.com.cn.w.kunlunno.com.
Name:	asset.watsons.com.cn.w.kunlunno.com
Address: 125.36.136.244 [中国 天津 天津]
Name:	asset.watsons.com.cn.w.kunlunno.com
Address: 125.36.180.241 [中国 天津 天津]

确认程序是正常工作的
nslookup playe.atnxty.com | nali
Server:		192.168.1.1 [局域网 局域网]
Address:	192.168.1.1 [局域网 局域网]#53

Non-authoritative answer:
playe.atnxty.com	canonical name = playe.atnxty.com.w.cdngslb.com [阿里云 CDN].
Name:	playe.atnxty.com.w.cdngslb.com [阿里云 CDN]
Address: 222.186.16.239 [中国 江苏 镇江]
Name:	playe.atnxty.com.w.cdngslb.com [阿里云 CDN]
Address: 58.215.158.239 [中国 江苏 无锡]

**Comment by zu1k** [comment]
没想到还有这个特殊的地方，修复了，感谢
