### ISSUE TITLE
Powershell脚本中使用小乱码

### ISSUE THREAD

**Issue by Doublefire-Chen** [zu1k/nali#180]
首先，非常感谢作者和贡献者们开发的优秀项目，你们辛苦了。
我在使用中遇到了一点小问题。
如下图，直接运用命令运行没有一点问题，但是当我把程序整合到脚本中运行时却不能正确显示结果
<img width="979" alt="Screenshot 2023-10-19 at 14 58 47" src="https://github.com/zu1k/nali/assets/72138342/f9a05967-69f1-4f2e-bcb9-27400a3d4091">

**Comment by zu1k** [comment]
请升级 PowerShell 到最新版

**Comment by Doublefire-Chen** [comment]
> 请升级 PowerShell 到最新版
这台服务器性能太弱了，windows server 2016，1C1G，我还是不升级powershell7了，怕带不动
目前的解决方案是用GEOIP2数据库，语言使用英文
谢谢作者答复
