### ISSUE TITLE
在通过调用qqwry.dat判断运营商之前，能否实现自定义一个private.dat自行设置IP对应运营商相关信息比如私网IP互联地址段

### ISSUE THREAD

**Issue by maojianyou** [zu1k/nali#181]
在通过调用qqwry.dat判断运营商之前，我可以自定义一个private.dat自行设置比如私网IP互联地址段不，比如 172.16.1.1  对应 电信出口，172.16.2.1 对应联通出口， 172.16.3.1 对应移动出口，还有其他qqwry.dat不准的数据库，也可以优先自定义，考虑性能可以支持100行，能否实现这个功能，这个是nali调用qqwry.dat运营商不准的完美补充

**Comment by zu1k** [comment]
如果有修改数据的需求，建议不要使用 qqwry，mmdb是比较常用且方便的格式，可以自行合并准确数据并生成最终 mmdb 数据库供nali查询
