### ISSUE TITLE
nali update 命令运行之后，会在用户根目录下面生成2个目录，并且与readme介绍的目录路径不一致。

### ISSUE THREAD

**Issue by zazitufu** [zu1k/nali#186]
1、使用的是root用户
2、nali这个执行文件放在其它目录（已在环境变量里增加那个目录，可以直接执行）
3、第一次执行`nali update`，会在root目录里面生成一个`.config ` 还有` .local `这两个目录（请看截图1里面运行update的前后目录对比），请问为什么与readme里面介绍的，保存目录位置不一致？
4、我需要如何操作，才能按照readme里面的，把nali的设置和下载的数据库，自动放置在readme指示的 `~/.nali` 这个路径下面

![image](https://github.com/zu1k/nali/assets/57139031/3619fa7e-c864-4191-8da7-40403a527a61)

![image](https://github.com/zu1k/nali/assets/57139031/52db7bad-ee00-4f2a-b8de-e20759961904)

**Comment by zu1k** [comment]
README 忘记改了，这两个目录是 XDG 标准目录，具体通过 `nali info` 查看

**Comment by zu1k** [comment]
已经修改 readme

**Comment by zazitufu** [comment]
虽然好像问题不大，不过看上去这个部分也建议改一下
![image](https://github.com/zu1k/nali/assets/57139031/470d9db8-ff35-451e-9f2e-ed330227f582)
