### ISSUE TITLE
pkg里边没有查询DB-IP数据库功能 .go?

### ISSUE THREAD

**Issue by OUZYcn** [zu1k/nali#188]
https://github.com/cnartlu/geoip2/issues/1#issuecomment-1865975263

目前我自己的体验来说，[ip-to-city-lite](https://db-ip.com/db/download/ip-to-city-lite ) 感觉比MaxMind GeoLite2-City数据质量要更丰富，质量更好。

**Comment by zu1k** [comment]
这个是支持的，见 https://github.com/zu1k/nali/blob/214d935a25edb87ca47c0449cf37160717410a32/internal/db/default.go#L46

**Comment by zu1k** [comment]
试试最新的 master 分支。 现在 geoip 可以在中文结果不存在的时候输出英文结果。

```
# NALI_DB_IP4=dbip-city-lite nali 103.167.135.39
103.167.135.39 [香港 Wanchai]
```

**Comment by OUZYcn** [comment]
感谢回复。

我后来去查看了[ case "DBIP-City-Lite",](https://github.com/oschwald/geoip2-golang/blob/fbe22892b33824e127ef49e61e84812d8d5497a6/reader.go#L285)
发现里边已经有DBIP-City-Lite的信息，因此尝试简单替换了GeoLite2-City.mmdb 为 dbip-city-lite.mmdb 
发现直接就可用，美滋滋。 

没有直接用你的代码，是因为我需要地理经纬度用于Grafana的Geomap dashboard
