### ISSUE TITLE
目前看cat mtr echo dig等linux/windows命令支持多种可以调用nali 浏览器是否可以支持显示

### ISSUE THREAD

**Issue by maojianyou** [zu1k/nali#194]
比如这个浏览器显示的html文本或者json内容,可以直接调用nali显示IP运营商归属地
![image](https://github.com/user-attachments/assets/279503e2-691b-4249-9491-e113c298421f)

**Comment by xqzr** [comment]
```batch
curl ip.sb | nali
```

**Comment by maojianyou** [comment]
> ```batchfile
> curl ip.sb | nali
> ```

浏览器，哥，你这是linux系统

**Comment by xqzr** [comment]
> > ```batchfile
> > curl ip.sb | nali
> > ```
> 
> 浏览器，哥，你这是linux系统

Windows 也支持

**Comment by maojianyou** [comment]
> > > ```batchfile
> > > curl ip.sb | nali
> > > ```
> > 
> > 
> > 浏览器，哥，你这是linux系统
> 
> Windows 也支持

我不是说windows curl不支持，我意思是浏览器上面直接调用，而不是cmd命令里面使用curl ，可以理解不
