### ISSUE TITLE
output error when the ip is repeated as a entire or as a substring

### ISSUE THREAD

**Issue by hyliang96** [zu1k/nali#22]
1. When then an ip is repeated like n times in a line, then in the output of `nali` for this line, the geological location will be repeated n times after everywhere the ip appears.

For example:

```bash
> echo '127.0.0.1 aaa' | nali
127.0.0.1 [本机地址] aaa

> echo '127.0.0.1 aaa 127.0.0.1' | nali
127.0.0.1 [本机地址] [本机地址] aaa 127.0.0.1 [本机地址] [本机地址]

> echo '127.0.0.1 aaa 127.0.0.1 bbbb 127.0.0.1' | nali
127.0.0.1 [本机地址] [本机地址] [本机地址] aaa 127.0.0.1 [本机地址] [本机地址] [本机地址] bbbb 127.0.0.1 [本机地址] [本机地址] [本机地址]

> echo '127.0.0.1 aa 127.0.0.2 aaaaa 127.0.0.1' | nali
127.0.0.1 [本机地址] [本机地址] aa 127.0.0.2 [局域网 IP] aaaaa 127.0.0.1 [本机地址] [本机地址]
```

2. When a line contains more than ips, where one ip is a subtring of another ip, the ips will be parsed incorrectly. For example:

```bash
# ipxxxx   ip
> echo '127.0.0.12 aa 127.0.0.1 bbb' | nali
127.0.0.1 [本机地址]2 [局域网 IP] aa 127.0.0.1 [本机地址] bbb

# ip  ipxxxx
> echo '127.0.0.1 aa 127.0.0.12 bbb' | nali
127.0.0.1 [本机地址] aa 127.0.0.1 [本机地址]2 bbb

# ip  xxxip
> echo '27.0.0.1 aa 127.0.0.1 bbb' | nali
27.0.0.1 [日本 东京都Amazon数据中心] aa 127.0.0.1 [本机地址] [日本 东京都Amazon数据中心] bbb

# xxxip   ip
> echo '127.0.0.1 aa 27.0.0.1 bbb' | nali
127.0.0.1 [日本 东京都Amazon数据中心] [本机地址] aa 27.0.0.1 [日本 东京都Amazon数据中心] bbb

# xxxipxxx ip
> echo '127.0.0.12 aa 27.0.0.1 bbb' | nali
127.0.0.1 [日本 东京都Amazon数据中心]2 [局域网 IP] aa 27.0.0.1 [日本 东京都Amazon数据中心] bbb

# ip    xxxxipxxxx
> echo '27.0.0.1 aa 127.0.0.12 bbb' | nali
27.0.0.1 [日本 东京都Amazon数据中心] aa 127.0.0.1 [日本 东京都Amazon数据中心]2 bbb
```

For different the aforementioned cases of the relations between the two ips, the fault is different.

**Comment by zu1k** [comment]
There is only one reason for these problems, I use replace to add geographic information.

These days I will use other methods to format the output to avoid these problems.

**Comment by zu1k** [comment]
Thanks for your PR, merged but not what I expected.

I hope that each character will be scanned only once, just like a lexical analyzer, the geographic information will be inserted after the IP is detected, instead of using strings.replace or regular replacement.

**Comment by zu1k** [comment]
AND still have problems

```
echo 127.0.0.1 ::127.0.0.1 |nali.exe
127.0.0.1 [本机地址] ::127 [IANA保留地址 ].0.0.1 [本机地址]
```

It can't distinguish between _IPv4 address_ and _IPv4-compatible IPv6 address_

**Comment by hyliang96** [comment]
These two problems are solved in submit2. Please check it and merge.

**Comment by hyliang96** [comment]
This is a more efficient way. Looking forward to your refactoring.

> I hope that each character will be scanned only once, just like a lexical analyzer, the geographic information will be inserted after the IP is detected, instead of using strings.replace or regexp replacement.
