### ISSUE TITLE
Not work with *.com.*.com

### ISSUE THREAD

**Issue by wolfogre** [zu1k/nali#40]
Some CDN providers use the source domain as the prefix of CNAME, like `a.com.qiniudns.com`.

Nali does not work with that:

```
$ echo a.a.qiniudns.com | nali
a.a.qiniudns.com [七牛云]

$ echo a.com.qiniudns.com | nali
a.com.qiniudns.com
```

**Comment by zu1k** [comment]
感谢反馈，前面竟然一直也没发现这个bug，试一下 v0.2.3 版本
