### ISSUE TITLE
go get安装未成功。go version go1.16.2 linux/arm

### ISSUE THREAD

**Issue by JohyC** [zu1k/nali#46]
以下是  go get -u -v github.com/zu1k/nali 执行返回。然后当前目录下没有文件产生。
请求指导！

![image](https://user-images.githubusercontent.com/38210128/115100812-ca5ac800-9f71-11eb-82c9-41232c34ddc0.png)

![image](https://user-images.githubusercontent.com/38210128/115100845-1e65ac80-9f72-11eb-8372-9982e836ee98.png)

**Comment by zu1k** [comment]
查看 $GOPATH/bin 下面

**Comment by JohyC** [comment]
> 查看 $GOPATH/bin 下面

明白了！谢谢大佬。
