### ISSUE TITLE
parseBaseCname Error

### ISSUE THREAD

**Issue by qbzysa** [zu1k/nali#66]
parseBaseCname() may be  error. eg:www.ucloud.cn.ucloud.com.cn

func parseBaseCname(url string) (string, error) {
	extract, err := tldextract.New(TldCachePath, false)
	if err != nil {
		return "", err
	}
	res := extract.Extract(url)
	rootDomain := res.Root + "." + res.Tld
	return rootDomain, nil
}

**Comment by zu1k** [comment]
感谢反馈，不过我认为tldextract不太符合我们的需求，并且需要引入额外的库，我使用其他方法解决了，请查看最新提交
