### ISSUE TITLE
中英文README对GO的安装版本要求不同

### ISSUE THREAD

**Issue by zhwandzcx** [zu1k/nali#74]
**以哪个为准?**
![image](https://user-images.githubusercontent.com/42031122/146401553-c83b9328-6db4-4fd4-a8d5-862ed8499dc6.png)
![image](https://user-images.githubusercontent.com/42031122/146401616-864d38db-ad6e-4bc6-89e7-3c1b7d7960d5.png)

**Comment by zu1k** [comment]
最新的提交使用了1.18里面独有的标准库，语言安装1.18-beta1

**Comment by laggardkernel** [comment]
@zu1k 为什么是 1.18，1.18 还是 beta 版本，未正式发布。

另外兄弟你的版本号没 `v` 前缀了，我打包脚本里直接改动版本号不能安装成功才发现的。是不是统一一下？

**Comment by zu1k** [comment]
新版中使用了1.18版中提供的netip库

后续版本不再使用v前缀了，可以通过访问 https://api.github.com/repos/zu1k/nali/releases 获取发版信息，无需手动修改打包脚本

**Comment by zu1k** [comment]
https://api.github.com/repos/zu1k/nali/releases/latest

**Comment by laggardkernel** [comment]
@zu1k 明白了，我还以为你只是 0.3.4 版本漏掉了 `v` 前缀。
