### ISSUE TITLE
不知道为什么会有编码问题. 

### ISSUE THREAD

**Issue by ihuanx** [zu1k/nali#76]
![](https://metaimg.cc/2021/12/28/meteimg.cc-7279d5a3f4740.jpg)
例子 `ping ifttt.com | nali`
nali-windows-amd64-0.3.5

**Comment by rampageX** [comment]
你们都不用 -h 的？？？

```
Flags:
      --gbk       Use GBK decoder
```

**Comment by ihuanx** [comment]
> 你们都不用 -h 的？？？
> 
> ```
> Flags:
>       --gbk       Use GBK decoder
> ```

感谢..  似乎有一点麻烦  已解决
