### ISSUE TITLE
WIN10 cmd输出乱码

### ISSUE THREAD

**Issue by niclau** [zu1k/nali#82]
C:\Users\user>tracert -d 208.54.80.99 |nali

ͨ������ 30 ��Ծ�����ٵ� 208.54.80.99 [美国]  ��·��

  1     1 ms    <1 ����   <1 ���� 192.168.2.4 [局域网 对方和您在同一内部网]
  2   240 ms   319 ms   320 ms  172.16.1.1 [局域网 对方和您在同一内部网]
  3   270 ms   319 ms   226 ms  140.91.194.153 [美国]
  4   264 ms   319 ms   219 ms  128.241.7.147 [美国 日本NTT通讯美洲公司]
  5   278 ms   321 ms   315 ms  128.241.7.146 [美国 日本NTT通讯美洲公司]
  6   245 ms   343 ms     *     129.250.3.237 [日本 NTT通信公司骨干网]
  7   253 ms   326 ms   311 ms  129.250.2.160 [日本 东京都NTT通信公司国际互联节点]
  8   272 ms   226 ms   228 ms  144.232.0.193 [美国 Sprint电信公司网络]
  9   349 ms   327 ms   312 ms  144.232.22.162 [美国 Sprint电信公司网络]
 10   254 ms   319 ms   319 ms  144.232.22.95 [美国 Sprint电信公司网络]
 11   273 ms   320 ms   240 ms  144.232.15.238 [美国 Sprint电信公司网络]
 12   276 ms   312 ms   321 ms  144.232.15.166 [美国 Sprint电信公司网络]
 13   594 ms   318 ms   318 ms  144.232.22.87 [美国 Sprint电信公司网络]
 14   595 ms   278 ms   271 ms  144.232.23.145 [美国 Sprint电信公司网络]
 15     *        *        *     ������ʱ��
 16     *        *        *     ������ʱ��

C:\Users\user>ping 208.67.220.220 | nali

���� Ping 208.67.220.220 [美国 加利福尼亚州旧金山市OpenDNS有限公司公众DNS服务器]  ���� 32 �ֽڵ�����:
���� 208.67.220.220 [美国 加利福尼亚州旧金山市OpenDNS有限公司公众DNS服务器]  �Ļظ�: �ֽ�=32 ʱ��=57ms TTL=52
���� 208.67.220.220 [美国 加利福尼亚州旧金山市OpenDNS有限公司公众DNS服务器]  �Ļظ�: �ֽ�=32 ʱ��=47ms TTL=52
���� 208.67.220.220 [美国 加利福尼亚州旧金山市OpenDNS有限公司公众DNS服务器]  �Ļظ�: �ֽ�=32 ʱ��=59ms TTL=52
���� 208.67.220.220 [美国 加利福尼亚州旧金山市OpenDNS有限公司公众DNS服务器]  �Ļظ�: �ֽ�=32 ʱ��=57ms TTL=52

208.67.220.220 [美国 加利福尼亚州旧金山市OpenDNS有限公司公众DNS服务器]  �� Ping ͳ����Ϣ:
    ���ݰ�: �ѷ��� = 4���ѽ��� = 4����ʧ = 0 (0% ��ʧ)��
�����г̵Ĺ���ʱ��(�Ժ���Ϊ��λ):
    ���� = 47ms��� = 59ms��ƽ�� = 55ms

**Comment by zu1k** [comment]
#59 #76
