### ISSUE TITLE
IPv6 数据库下载链接失效

### ISSUE THREAD

**Issue by bobbyz3g** [zu1k/nali#84]
IPv6 数据库的 URL https://ip.zxinc.org/ip.7z 返回 nginx error， 导致更新数据库时会发生 panic.

**Comment by labulakalia** [comment]
我这里 下载地址也404
```
➜  ~ axel https://ip.zxinc.org/ip.7z
Initializing download: https://ip.zxinc.org/ip.7z
ERROR 404: Not Found.
```
在这里下载了 不过更新是半年前了 https://github.com/Rhilip/ipv6wry.db/blob/master/ipv6wry.db

**Comment by zu1k** [comment]
我需要更多信息，包括你们的域名解析结果、运营商等信息

**Comment by zu1k** [comment]
看样子`ip.zxinc.org`国内解析结果`101.32.207.56`返回404
国外解析结果`45.32.23.221`没有问题

`curl -vv4 https://ip.zxinc.org/ip.7z --resolve 'ip.zxinc.org:443:45.32.23.221'`

综上，建议翻墙

**Comment by Kaiser925** [comment]
经由国内 DNS 服务器解析的地址都是有误的，由 8.8.8.8 和 1.1.1.1 解析则是没问题的

**Comment by zu1k** [comment]
已联系zx维护大佬修复，感谢！
