### ISSUE TITLE
win10  update  ipv6 总是报错，重启也不行。

### ISSUE THREAD

**Issue by ultrang** [zu1k/nali#91]
![image](https://user-images.githubusercontent.com/17217102/162475202-d9539833-b15e-470a-bd36-5cf4249c6241.png)

win10  update  ipv6 总是报错，重启也不行。

centos下没问题。
[root@localhost bin]# /usr/local/bin/nali update
2022/04/08 23:34:57 正在下载最新 纯真 IPv4数据库...
2022/04/08 23:35:02 已将最新的 纯真IP库 保存到本地: [/root/.nali/qqwry.dat]
2022/04/08 23:35:02 正在下载最新 ZX IPv6数据库...
2022/04/08 23:35:03 已将最新的 ZX IPv6数据库 保存到本地: [/root/.nali/zxipv6wry.db]
ll2022/04/08 23:35:07 已将最新的 ip2region 保存到本地: [/root/.nali/ip2region.db]
2022/04/08 23:35:07 正在下载最新 CDN服务提供商数据库...

2022/04/08 23:35:08 已将最新的 CDN数据库 保存到本地: [/root/.nali/cdn.yml]

**Comment by zu1k** [comment]
手动删除旧文件

**Comment by ultrang** [comment]
> 手动删除旧文件

C:\Users\xxx\AppData\Local\Temp\  下的随机数字文件删除掉了，也不行。
c:\Users\xxx\.nali\ 路径下只有qqwry.dat一个文件。

暂时是从centos下，把几个db文件copy到win下来用。

**Comment by zu1k** [comment]
看你提示是被另一个进程占用，能不能查一下，或者关闭杀毒软件试试

**Comment by ultrang** [comment]
关闭防火墙，没起作用，同样的提示。
换了一台win，也是同样的提示。

![image](https://user-images.githubusercontent.com/17217102/162616535-62511e59-39ab-4d81-98e6-2843ad0b07bf.png)

**Comment by zu1k** [comment]
刚刚在windows下复现了，等我检查一下哪里问题

**Comment by zu1k** [comment]
试一下 0.3.9 版本

**Comment by ultrang** [comment]
> 

刚试了，没问题。
感谢大佬。
