### ISSUE TITLE
执行安装命令报错

### ISSUE THREAD

**Issue by gzj1984** [zu1k/nali#92]
安装命令go install github.com/zu1k/nali，提示“go install github.com/zu1k/nali@latest”，然后用这条命令执行后又提示module github.com/zu1k/nali: Get "https://proxy.golang.org/github.com/zu1k/nali/@v/list": dial tcp 172.217.160.81:443: i/o timeout，怎么回事

**Comment by zu1k** [comment]
你写没挂代理啊，需要翻墙
